version: '2'

tasks:
  docker-build:
    cmds:
      - docker build -t rnkoaa/apricot .
      
  docker-run:
    cmds:
      - docker run -it -p 3000:3000 -e NODE_ENV=dev --add-host=vagrant-hashi-stack-1.alpha.consul:192.168.33.10 --name apricot rnkoaa/apricot
 
  docker-push:
    cmds:
      - docker build --no-cache -t rnkoaa/apricot:0.0.1 .
      - docker tag rnkoaa/apricot:0.0.1 rnkoaa/apricot:latest
      - docker push rnkoaa/apricot:0.0.1
      - docker push rnkoaa/apricot:latest
  
  docker-cleanup:
    cmds:
      - docker rm -f apricot

  install-deps:
    cmds:
      - npm install
      
  serve:
    cmds:
      - node dist/server.js

  build:
    cmds:
      - gulp
  
  # Rebuild project before serve
  build-serve:
    deps: ['build']
    cmds:
      - node dist/server.js

  run:
    desc: "Build and Run the Index File."
    deps: ['build']
    cmds:
      - node dist/service/index.js

  clean:
    cmds:
      - rm -rf dist

  deep-clean:
    deps: ['clean']
    cmds:
      - rm -rf node_modules

  run-only:
    desc: "Run ad-hoc index file, assumes application is already built"
    cmds:
      - node dist/service/index.js