version: '2'

tasks:
  docker-build:
    cmds:
      - docker build -t rnkoaa/banana .
      
  docker-run:
    cmds:
      - docker run -it -p 3000:3000 -e NODE_ENV=dev --add-host=vagrant-hashi-stack-1.alpha.consul:192.168.33.10 --name banana rnkoaa/banana
 
  docker-push:
    cmds:
      - docker build --no-cache -t rnkoaa/banana:0.0.1 .
      - docker tag rnkoaa/banana:0.0.1 rnkoaa/banana:latest
      - docker push rnkoaa/banana:0.0.1
      - docker push rnkoaa/banana:latest
  
  docker-cleanup:
    cmds:
      - docker rm -f banana

  install-deps:
    cmds:
      - npm install
      
  serve:
    cmds:
      - node dist/server.js

  build:
    cmds:
      - gulp
  
  # Rebuild project before serve
  build-serve:
    deps: ['build']
    cmds:
      - node dist/server.js

  run:
    desc: "Build and Run the Index File."
    deps: ['build']
    cmds:
      - node dist/index.js

  clean:
    cmds:
      - rm -rf dist

  deep-clean:
    deps: ['clean']
    cmds:
      - rm -rf node_modules

  run-only:
    cmds:
      - node dist/index.js